name: linting, testing, building
on:
    push:
        branches: [master]
    pull_request:
        branches: [master]
jobs:
  pipeline:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [17.x]
    runs-on: ubuntu-latest
    steps:
        - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1.4.3
        with:
          node-version: ${{ matrix.node }}
        - name: Install dependencies
        run: npm install
        - name: build project prod
        run: npm run build:prod
        - name: linting typescript
        run: npm run lint:ts
        - name: linting scss
        run: npm run lint:scss
        - name: unit test
        run: npm run test:unit
