name: linting, testing, building
on:
    push:
        branches: [master]
    pull_request:
        branches: [master]
jobs:
    pipeline:
        strategy:
            matrix:
                os: [ubuntu-latest]
                node: [17.x]
        runs-on: ubuntu-lates
        steps:
            - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
