name: linting, testing, building
on:
    push:
        branches: [master]
    pull_request:
        branches: [master]
jobs:
    pipeline:
        strategy:
            matrix:
                os: [ubuntu-latest]
                node: [17.x]
        runs-on: ubuntu-lates
        steps:
          - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
            - name: Checkout
              uses: actions/checkout@v3
            - name: Setup node
              uses: actions/setup-node@v3
              with:
                  node-version: 16.13.x
                  cache: npm
            - name: Install dependencies
              run: npm install
            - name: build project prod
              run: npm run build:prod
            - name: linting typescript
              run: npm run lint:ts
            - name: linting scss
              run: npm run lint:scss
            - name: unit test
              run: npm run test:unit
