name: linting, testing, building
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    pipeline:
        strategy:
            matrix:
                os: [ubuntu-latest]
                node: [17]
        runs-on: ${{ matrix.os }}

        steps:
            - name: Setup Node.js environment
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node }}
            - name: Checkout main branch
              uses: actions/checkout@v2
            - name: Cache node_modules
              uses: actions/cache@v2.1.0
              with:
                  # A list of files, directories, and wildcard patterns to cache and restore
                  path: node_modules
                  # An explicit key for restoring and saving the cache
                  key: ${{ matrix.os }}-node-v${{ matrix.node }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/package-lock.json')) }}

            - name: Install dependencies
              if: steps.cache.outputs.cache-hit != 'true'
              run: npm install
            - name: build production project
              run: npm run build:prod
            - name: linting typescript
              run: npm run lint:ts
            - name: linting css
              run: npm run lint:scss
            - name: unit testing
              run: npm run test:unit
            - name: build storybook
              run: npm run storybook:build
            - name: screenshot testing
              run: npm run test:ui:ci
